export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const DEL = 'DEL'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const EDIT_TODO = 'EDIT_TODO'
export const UPDATE= 'UPDATE'